FROM golang:1.25-alpine AS build
WORKDIR /src
COPY go.work go.work
COPY pkg/ pkg/
COPY gen/ gen/
COPY herald/ herald/
RUN cd herald && go build -ldflags="-s -w" -o /delivery-worker ./cmd/delivery-worker

FROM gcr.io/distroless/static-debian12:nonroot
COPY --from=build /delivery-worker /delivery-worker
EXPOSE 8092
USER nonroot:nonroot
ENTRYPOINT ["/delivery-worker"]
