package rules

import (
	"fmt"
	"sync"
	"time"

	"go.uber.org/zap"

	pb "github.com/AudreyRodrygo/Inch/gen/inch/v1"
)

// Result represents an alert generated by the rule engine.
type Result struct {
	Rule       *Rule
	GroupKey   string
	EventCount int
	EventIDs   []string
}

// Engine evaluates security events against correlation rules.
//
// It is the central component that ties together:
//   - Single-event matching (immediate field checks)
//   - Temporal correlation (sliding window thresholds)
//   - Sequence detection (ordered event chains / kill chains)
//
// Thread safety: the engine is safe for concurrent use.
// Rules are protected by RWMutex (many readers, one writer for hot reload).
// Window and sequence trackers have their own synchronization.
type Engine struct {
	mu      sync.RWMutex
	rules   []*Rule
	windows *WindowTracker
	seqs    *SequenceTracker
	logger  *zap.Logger
}

// New creates a rule engine with the given rules.
func New(rules []*Rule, logger *zap.Logger) *Engine {
	return &Engine{
		rules:   rules,
		windows: NewWindowTracker(),
		seqs:    NewSequenceTracker(),
		logger:  logger,
	}
}

// Evaluate checks an event against all active rules.
//
// Returns a list of results (alerts) for rules that fired.
// Most events won't match any rule — the function returns nil.
//
// This is called for every event in the pipeline, so performance matters.
// Single-event rules are O(N×M) where N=rules and M=conditions per rule.
func (e *Engine) Evaluate(event *pb.SecurityEvent) []Result {
	e.mu.RLock()
	rules := e.rules
	e.mu.RUnlock()

	var results []Result

	now := time.Now()
	if event.Timestamp != nil {
		now = event.Timestamp.AsTime()
	}

	for _, rule := range rules {
		if !rule.IsEnabled() {
			continue
		}

		switch rule.Type {
		case RuleTypeSingle:
			if result, ok := e.evalSingle(event, rule); ok {
				results = append(results, result)
			}

		case RuleTypeThreshold:
			if result, ok := e.evalThreshold(event, rule, now); ok {
				results = append(results, result)
			}

		case RuleTypeSequence:
			if result, ok := e.evalSequence(event, rule); ok {
				results = append(results, result)
			}
		}
	}

	return results
}

// evalSingle checks if the event matches all conditions of a single rule.
func (e *Engine) evalSingle(event *pb.SecurityEvent, rule *Rule) (Result, bool) {
	if !MatchesConditions(event, rule.Conditions) {
		return Result{}, false
	}

	return Result{
		Rule:       rule,
		GroupKey:   GetGroupKey(event, rule.GroupBy),
		EventCount: 1,
		EventIDs:   []string{event.EventId},
	}, true
}

// evalThreshold checks if the event pushes a sliding window over its threshold.
func (e *Engine) evalThreshold(event *pb.SecurityEvent, rule *Rule, now time.Time) (Result, bool) {
	// First check if the event matches the rule's conditions.
	if !MatchesConditions(event, rule.Conditions) {
		return Result{}, false
	}

	// Build the window key: "rule_id|group_value".
	groupKey := GetGroupKey(event, rule.GroupBy)
	windowKey := fmt.Sprintf("%s|%s", rule.ID, groupKey)

	fired, count := e.windows.AddAndCheck(windowKey, now, rule.Window, rule.Threshold)
	if !fired {
		return Result{}, false
	}

	e.logger.Info("threshold rule fired",
		zap.String("rule", rule.ID),
		zap.String("group", groupKey),
		zap.Int("count", count),
	)

	return Result{
		Rule:       rule,
		GroupKey:   groupKey,
		EventCount: count,
		EventIDs:   []string{event.EventId},
	}, true
}

// evalSequence checks if the event advances a sequence rule's state machine.
func (e *Engine) evalSequence(event *pb.SecurityEvent, rule *Rule) (Result, bool) {
	groupKey := GetGroupKey(event, rule.GroupBy)
	seqKey := fmt.Sprintf("%s|%s", rule.ID, groupKey)

	if !e.seqs.Evaluate(seqKey, event, rule) {
		return Result{}, false
	}

	e.logger.Info("sequence rule fired",
		zap.String("rule", rule.ID),
		zap.String("group", groupKey),
	)

	return Result{
		Rule:       rule,
		GroupKey:   groupKey,
		EventCount: len(rule.Steps),
		EventIDs:   []string{event.EventId},
	}, true
}

// Reload atomically replaces the rule set.
//
// This is used for hot reload — when YAML files change on disk,
// the new rules are loaded and swapped in without stopping the engine.
// In-flight evaluations continue with the old rules until they complete.
func (e *Engine) Reload(rules []*Rule) {
	e.mu.Lock()
	e.rules = rules
	e.mu.Unlock()

	e.logger.Info("rules reloaded", zap.Int("count", len(rules)))
}

// Rules returns the current rule set (for inspection/testing).
func (e *Engine) Rules() []*Rule {
	e.mu.RLock()
	defer e.mu.RUnlock()
	return e.rules
}

// StartCleanup runs periodic cleanup of expired window and sequence state.
// Call this in a goroutine: go engine.StartCleanup(ctx, time.Minute)
func (e *Engine) StartCleanup(done <-chan struct{}, interval time.Duration) {
	ticker := time.NewTicker(interval)
	defer ticker.Stop()

	for {
		select {
		case <-done:
			return
		case <-ticker.C:
			e.windows.Cleanup(10 * time.Minute)
			e.seqs.Cleanup(10 * time.Minute)
		}
	}
}
